const express = require('express');
const router = express.Router();
const Order = require('../models/Order');
const User = require('../models/User');
const { protect, adminOnly } = require('../middleware/auth');

// @POST /api/orders — place order (HIGH SECURITY)
router.post('/', protect, async (req, res) => {
  try {
    const { items, billing, payment, subtotal, tax, shipping, total, notes } = req.body;
    
    // 1. High-Security Payment Validation (Simulated)
    if (payment.method === 'card') {
      if (!payment.cardInfo || !payment.otp) {
        return res.status(400).json({ success: false, message: 'High-security OTP verification required for card payments.' });
      }
      // Simulate bank-level verification delay
      console.log(`🔐 Verifying Card ending in ${payment.cardInfo.last4}...`);
      if (payment.otp !== '123456') { // Mock OTP check
        return res.status(401).json({ success: false, message: 'Invalid Security OTP. Transaction declined.' });
      }
    }

    const userRegion = req.user.region || 'IN';
    
    // 2. Create Order with Payment Status
    const order = await Order.create({
      user: req.user._id,
      items, 
      billing, 
      payment: {
        ...payment,
        status: 'paid', // Mark as paid after OTP success
        paidAt: Date.now(),
        transactionId: `TXN-${crypto.randomBytes(8).toString('hex').toUpperCase()}`
      }, 
      subtotal, 
      tax, 
      shipping, 
      total, 
      currency: userRegion === 'IN' ? 'INR' : 'USD',
      notes
    });

    // 3. Amount Credit Simulation
    console.log(`💰 Crediting ${order.total} ${order.currency} to EduSync Master Account...`);

    // 4. EduSync Internal Billing Tool (Invoice Generation)
    const { generateInternalInvoice } = require('../utils/billingService');
    const invoiceResult = await generateInternalInvoice(order, req.user);
    
    // Update order with our own invoice info
    order.notes = `Official Invoice: ${invoiceResult.invoiceId}`;
    await order.save();

    // 5. Clear user cart
    await User.findByIdAndUpdate(req.user._id, { cart: [] });
    
    res.status(201).json({ 
      success: true, 
      message: 'Payment Successful. Invoice generated by EduSync Billing Tool.',
      order,
      invoice: invoiceResult
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// @GET /api/orders/my — user's orders
router.get('/my', protect, async (req, res) => {
  try {
    const orders = await Order.find({ user: req.user._id })
      .populate('items.product', 'name images')
      .sort({ createdAt: -1 });
    res.json({ success: true, orders });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// @GET /api/orders/:id — single order
router.get('/:id', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id).populate('items.product');
    if (!order) return res.status(404).json({ success: false, message: 'Order not found' });
    if (order.user.toString() !== req.user._id.toString() && req.user.role !== 'admin')
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    res.json({ success: true, order });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ADMIN ROUTES
// @GET /api/orders — all orders (admin)
router.get('/', protect, adminOnly, async (req, res) => {
  try {
    const orders = await Order.find()
      .populate('user', 'name email')
      .populate('items.product', 'name')
      .sort({ createdAt: -1 });
    res.json({ success: true, count: orders.length, orders });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// @PUT /api/orders/:id/status — update order status (admin)
router.put('/:id/status', protect, adminOnly, async (req, res) => {
  try {
    const order = await Order.findByIdAndUpdate(
      req.params.id,
      { status: req.body.status, updatedAt: Date.now() },
      { new: true }
    );
    res.json({ success: true, order });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// @POST /api/orders/verify — verify payment signature
router.post('/verify', protect, async (req, res) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature, order_id } = req.body;
    const { verifyPaymentSignature } = require('../utils/paymentService');

    const isValid = verifyPaymentSignature(razorpay_order_id, razorpay_payment_id, razorpay_signature);

    if (isValid) {
      const order = await Order.findByIdAndUpdate(order_id, {
        status: 'Processing',
        'payment.status': 'Paid',
        'payment.transactionId': razorpay_payment_id,
        'payment.razorpayOrderId': razorpay_order_id
      }, { new: true });

      // Send Confirmation Email
      try {
        const sendEmail = require('../utils/sendEmail');
        await sendEmail({
          email: req.user.email,
          subject: 'Order Confirmed - EduSync',
          html: `<h3>Thank you for your order!</h3><p>Your order #${order._id} has been successfully placed.</p>`
        });
      } catch (e) { console.error('Confirmation email failed'); }

      res.json({ success: true, message: 'Payment verified', order });
    } else {
      res.status(400).json({ success: false, message: 'Invalid signature' });
    }
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;
